name: LibraChess PR vs Main Match

on:
  pull_request:
    branches: [main]
jobs:
  vs-match:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build PR engine
        run: |
          go build -o libra-pr main.go

      - name: Checkout main branch to ./main-engine
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-engine

      - name: Build main engine
        run: |
          cd main-engine
          go build -o libra-main main.go
          mv libra-main ../libra-main

      - name: Download cutechess-cli
        run: |
          wget -q https://github.com/cutechess/cutechess/releases/download/v1.3.0-beta7/cutechess-cli-1.3.0-beta7-linux64.tar.gz
          tar -xzf cutechess-cli-1.3.0-beta7-linux64.tar.gz

      - name: Install Qt5 dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y -qq libqt5core5a

      - name: Run cutechess match
        run: |
          ./cutechess-cli/cutechess-cli \
            -engine name=PullLibra cmd=./libra-pr \
            -engine name=MainLibra cmd=./libra-main \
            -each proto=uci tc=180+2 \
            -games 30 \
            -concurrency 1 \
            -openings file=books/chess.epd format=epd order=random plies=8 \
            -draw movenumber=40 movecount=6 score=10 \
            -ratinginterval 10 \
            -rounds 1
